[build]
  command = ""          # no build step for plain HTML/CSS/JS
  publish = "Main Menu" # <-- change to the folder you chose

# If this is a single-page app (client-side routing), uncomment:
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
